box      = 'precise_lxc'
hostname = 'maquina1'
domain   = 'example.com'
ip       = '192.168.40.42'
url      = 'http://bit.ly/vagrant-lxc-precise64-2013-10-23'

Vagrant.configure("2") do |config|
  config.vm.box = box
#  config.vm.box_url = url
  config.vm.hostname = hostname #+ '.' + domain
#  config.vm.network :private_network, ip: ip
#  config.vm.network :public_network
#  config.vm.network :forwarded_port, guest: 80, host: 8080
#  config.vm.synced_folder "../data", "/vagrant_data"

#   config.vm.provision "shell", inline: "yum update -y"

end
