#!/bin/bash

echo "cmd=/usr/lib64/nagios/plugins/check_calltrace.sh" > calltrace
echo "cmd=/usr/lib64/nagios/plugins/check_cpu.sh" > cpu 
echo "cmd=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -W 20% -K 10% " > disk
echo "cmd=/usr/lib64/nagios/plugins/check_fs_writable.py" > fs_writable
echo "cmd=/usr/lib64/nagios/plugins/check_load -w 15,10,10 -c 30,25,25" > load
echo "cmd=/usr/lib64/nagios/plugins/check_mountpoints_nfs.sh -A" > mountpoints
echo "cmd=/usr/lib64/nagios/plugins/check_netinterfaces.py " > netinterfaces
echo "cmd=/usr/lib64/nagios/plugins/check_open_fds.sh -W 75 -C 90" > open_fds
echo "cmd=/usr/lib64/nagios/plugins/check_open_files.pl -w 50 -c 80" > open_files
echo "cmd=/usr/lib64/nagios/plugins/check_pmp_memory.sh -w 70 -c 90" > memory
echo "cmd=/usr/lib64/nagios/plugins/check_procs -w 5 -c 10 -s Z" > zombie_procz
echo "cmd=/usr/lib64/nagios/plugins/check_ssh -t 10 localhost" > ssh
echo "cmd=/usr/lib64/nagios/plugins/check_swap -a -w 99% -c 40%" > swap
echo "cmd=/usr/lib64/nagios/plugins/check_uptime.pl -f -w 25" > uptime
echo "cmd=/usr/lib64/nagios/plugins/check_users -w 5 -c 10" > users
echo "cmd=/usr/lib64/nagios/plugins/check_tcp -H 2.3.4.5 -w 5 -c 10" > tcp_fallo_1
echo "cmd=/usr/lib64/nagios/plugins/check_tcp -H 12.13.14.15 -w 5 -c 10" > tcp_fallo_2
echo "cmd=/usr/lib64/nagios/plugins/check_http -H 2.3.24.15 -w 5 -c 10" > http_fallo_2

yum install -y nagios-plugins-users nagios-plugins-load nagios-plugins-procs nagios-plugins-disk nagios-plugins-ssh nagios-plugins-swap nagios-plugins-tcp nagios-plugins-http dsmctools-commonlinux-memory dsmctools-commonlinux-fswritable dsmctools-commonlinux-mountpointsnfs dsmctools-commonlinux-openfds dsmctools-commonlinux-calltrace dsmctools-commonlinux-cpu dsmctools-commonlinux-uptime dsmctools-commonlinux-openfiles dsmctools-commonlinux-netinterfaces
