# https://github.com/openstack/heat/blob/havana-eol/heat/engine/resources/server.py

heat_template_version: 2013-05-23

description: >
  Create a server and his port

parameters:
  name:
    type: string
    description: Name of the server
  key_name:
    type: string
    description: Name of keypair to assign to servers
  image:
    type: string
    description: Name of image to use for servers
  flavor:
    type: string
    description: Flavor to use for servers
  net_id:
    type: string
    description: ID of Neutron network into which servers get deployed
  subnet_id:
    type: string
    description: ID of Neutron sub network into which servers get deployed
  sec_groups:
    type: comma_delimited_list
    description: Name of the security groups. Eg.: "sec1,sec2"
  availability_zone:
    type: string
    description: availability zone to be deployed the server

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      security_groups: { get_param: sec_groups }
      availability_zone: { get_param: availability_zone }
      # A map of files to create/overwrite on the server upon boot. Keys are file names and values are the file contents.
      # Icehouse
      personality:
        /root/.ssh/coms_rsa:
          get_param: private_key
        /etc/salt/grains:
          str_replace:
            template: "roles: [$roles]"
            params:
              $roles:
                get_param: minion-roles
      networks:
        #- port: { get_resource: server_port }
        - uuid: { get_resource: net_id }

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: net_id }
      fixed_ips:
        - subnet_id: { get_param: subnet_id }
        #- ip_address: "a.b.c.d" # Por si queremos fijar la ip a mano
