# Permite leer en todos los NS el secret "dockerconfig"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-secret-dockerconfig
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  resourceNames:
  - dockerconfigjson
  verbs:
  - get
