FROM python:3.7-slim

WORKDIR /usr/src/app

RUN pip install --no-cache-dir pipenv

COPY Pipfile Pipfile.lock ./

RUN pipenv install --system

COPY * ./

ENTRYPOINT [ "python", "./zabbix-etl.py" ]

CMD [ "--help" ]
