require File.expand_path('~/.aws/aws_credentials.rb')

Vagrant.configure("2") do |config|

# AWS data #
access_key_id=@access_key_id # Dado al crear el usuario en Amazon IAM
secret_access_key=@secret_access_key # Dado al crear el usuario en Amazon IAM
box="dummy"
instance_type="t1.micro"
sec_groups = ["vagrant"] # Para poner mas Sec group: ["default","group2"]

 # Virginia (default)
ami = "ami-35792c5c" # Virginia Amazon linux
ssh_username="ec2-user" # Depende de la AMI

#ami = "ami-eb6b0182" # Virginia CentOS updated (root user)
ssh_username="root" # Depende de la AMI

#ami = "ami-867edcef" # Virginia Ubuntu 12.04 LTS
ssh_username="ubuntu" # Depende de la AMI

priv_key=File.expand_path("~/.aws/vagrantVIR.pem")
keypair_name="vagrantVIR" # El nombre de uno de los keypair que haya creado en la availability zone que vaya a usar
region = "us-east-1"


 # Ireland
#ami = "ami-149f7863" # Ireland Amazon linux
#ssh_username="ec2-user" # Depende de la AMI

#ami = "ami-230b1b57" # Ireland CentOS updated (root user)
#ssh_username="root" # Depende de la AMI

#ami = "ami-f7b6b383" # Ireland Ubuntu 12.04 LTS
#ssh_username="ubuntu" # Depende de la AMI

#priv_key=File.expand_path("~/.aws/vagrantEU.pem")
#keypair_name="vagrantEU" # El nombre de uno de los keypair que haya creado en la availability zone que vaya a usar
#region = "eu-west-1"

# AWS data #

    config.vm.box = box

    config.ssh.private_key_path = priv_key

    config.vm.provider :aws do |aws, override|
      aws.access_key_id=access_key_id 
      aws.secret_access_key=secret_access_key
      aws.keypair_name = keypair_name
      aws.instance_type = instance_type
      aws.ami = ami
      aws.security_groups = sec_groups 
      aws.region = region
      override.ssh.username = ssh_username
#      aws.elastic_ip = true #?
      aws.tags = {
        'Deployer' => "vagrant"
      }
    end
end
