# http://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html
# local_action vs delegate_to localhost
#
# Si no existe "localhost" en el inventario, ansible lo crea:
# https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html
#
#
# http://docs.ansible.com/playbooks_delegation.html#local-playbooks
- name: a play that runs entirely on the ansible host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: prueba
    command: echo "hola"

# Tambien se puede poner una task como local:
#- name: create tempfile
#  command: dd if=/dev/urandom of=/tmp/random.txt count=100
#  connection: local
# No funciona!


# Ad-hoc
ansible localhost -c local -a id
